variable "environment" {}
variable "project" {}
variable "createdby" {}
variable "rg_name" {}
variable "location" {}
variable "vnetcidr" {}
variable "bastioncidr" {}
variable "websubnetcidr" {}
variable "appsubnetcidr" {}
variable "dbsubnetcidr" {}
variable "web_host_name" {}
variable "web_username" {}
variable "web_os_password" {}
variable "app_username" {}
variable "app_admin_password" {}
variable "sqladminuser" {}
variable "sqladminpw" {}
variable "admin-mgt-ip" {}