variable "location" {}
variable "virtual_network_id" {}
variable "resource_group" {}
variable "web_subnet_id" {}
variable "web_host_name" {}
variable "web_username" {}
variable "web_os_password" {}
variable "environment" {}
variable "project" {}
variable "createdby" {}